defmodule Phrasing.Dict.Language do
  use Ecto.Schema
  import Ecto.Changeset

  schema "languages" do
    field :code, :string
    field :flag_code, :string
    field :name, :string
    has_many :translations, Phrasing.Dict.Translation
    has_many :entries, Phrasing.Dict.Entry
    has_many :cards, Phrasing.SRS.Card
    has_many :card_translations, Phrasing.SRS.Card, foreign_key: :translation_id
    has_many :songs, Phrasing.Library.Song
    has_many :books, Phrasing.Library.Book
    has_many :scripts, Phrasing.Library.Script

    timestamps()
  end

  @doc false
  def changeset(language, attrs) do
    language
    |> cast(attrs, [:name, :code, :flag_code])
    |> validate_required([:name, :code, :flag_code])
  end

  @doc """
  ISO-3166 Alpha 2 Codes mapped to country name
  """
  @alpha_2_codes %{
    "af" => "Afghanistan",
    "ax" => "Åland Islands",
    "al" => "Albania",
    "dz" => "Algeria",
    "as" => "American Samoa",
    "ad" => "Andorra",
    "ao" => "Angola",
    "ai" => "Anguilla",
    "aq" => "Antarctica",
    "ag" => "Antigua and Barbuda",
    "ar" => "Argentina",
    "am" => "Armenia",
    "aw" => "Aruba",
    "au" => "Australia",
    "at" => "Austria",
    "az" => "Azerbaijan",
    "bs" => "Bahamas",
    "bh" => "Bahrain",
    "bd" => "Bangladesh",
    "bb" => "Barbados",
    "by" => "Belarus",
    "be" => "Belgium",
    "bz" => "Belize",
    "bj" => "Benin",
    "bm" => "Bermuda",
    "bt" => "Bhutan",
    "bo" => "Bolivia (Plurinational State of)",
    "bq" => "Sint Eustatius and Saba, Bonaire",
    "ba" => "Bosnia and Herzegovina",
    "bw" => "Botswana",
    "bv" => "Bouvet Island",
    "br" => "Brazil",
    "io" => "British Indian Ocean Territory",
    "bn" => "Brunei Darussalam",
    "bg" => "Bulgaria",
    "bf" => "Burkina Faso",
    "bi" => "Burundi",
    "cv" => "Cabo Verde",
    "kh" => "Cambodia",
    "cm" => "Cameroon",
    "ca" => "Canada",
    "ky" => "Cayman Islands",
    "cf" => "Central African Republic",
    "td" => "Chad",
    "cl" => "Chile",
    "cn" => "China",
    "cx" => "Christmas Island",
    "cc" => "Cocos (Keeling) Islands",
    "co" => "Colombia",
    "km" => "Comoros",
    "cg" => "Congo",
    "cd" => "Democratic Republic of the Congo",
    "ck" => "Cook Islands",
    "cr" => "Costa Rica",
    "ci" => "Côte d'Ivoire",
    "hr" => "Croatia",
    "cu" => "Cuba",
    "cw" => "Curaçao",
    "cy" => "Cyprus",
    "cz" => "Czechia",
    "dk" => "Denmark",
    "dj" => "Djibouti",
    "dm" => "Dominica",
    "do" => "Dominican Republic",
    "ec" => "Ecuador",
    "eg" => "Egypt",
    "sv" => "El Salvador",
    "gq" => "Equatorial Guinea",
    "er" => "Eritrea",
    "ee" => "Estonia",
    "sz" => "Eswatini",
    "et" => "Ethiopia",
    "fk" => "Falkland Islands (Malvinas)",
    "fo" => "Faroe Islands",
    "fj" => "Fiji",
    "fi" => "Finland",
    "fr" => "France",
    "gf" => "French Guiana",
    "pf" => "French Polynesia",
    "tf" => "French Southern Territories",
    "ga" => "Gabon",
    "gm" => "Gambia",
    "ge" => "Georgia",
    "de" => "Germany",
    "gh" => "Ghana",
    "gi" => "Gibraltar",
    "gr" => "Greece",
    "gl" => "Greenland",
    "gd" => "Grenada",
    "gp" => "Guadeloupe",
    "gu" => "Guam",
    "gt" => "Guatemala",
    "gg" => "Guernsey",
    "gn" => "Guinea",
    "gw" => "Guinea-Bissau",
    "gy" => "Guyana",
    "ht" => "Haiti",
    "hm" => "Heard Island and McDonald Islands",
    "va" => "Holy See",
    "hn" => "Honduras",
    "hk" => "Hong Kong",
    "hu" => "Hungary",
    "is" => "Iceland",
    "in" => "India",
    "id" => "Indonesia",
    "ir" => "Iran (Islamic Republic of)",
    "iq" => "Iraq",
    "ie" => "Ireland",
    "im" => "Isle of Man",
    "il" => "Israel",
    "it" => "Italy",
    "jm" => "Jamaica",
    "jp" => "Japan",
    "je" => "Jersey",
    "jo" => "Jordan",
    "kz" => "Kazakhstan",
    "ke" => "Kenya",
    "ki" => "Kiribati",
    "kp" => "Korea (Democratic People's Republic of)",
    "kr" => "Republic of Korea",
    "kw" => "Kuwait",
    "kg" => "Kyrgyzstan",
    "la" => "Lao People's Democratic Republic",
    "lv" => "Latvia",
    "lb" => "Lebanon",
    "ls" => "Lesotho",
    "lr" => "Liberia",
    "ly" => "Libya",
    "li" => "Liechtenstein",
    "lt" => "Lithuania",
    "lu" => "Luxembourg",
    "mo" => "Macao",
    "mg" => "Madagascar",
    "mw" => "Malawi",
    "my" => "Malaysia",
    "mv" => "Maldives",
    "ml" => "Mali",
    "mt" => "Malta",
    "mh" => "Marshall Islands",
    "mq" => "Martinique",
    "mr" => "Mauritania",
    "mu" => "Mauritius",
    "yt" => "Mayotte",
    "mx" => "Mexico",
    "fm" => "Micronesia (Federated States of)",
    "md" => "Republic of Moldova",
    "mc" => "Monaco",
    "mn" => "Mongolia",
    "me" => "Montenegro",
    "ms" => "Montserrat",
    "ma" => "Morocco",
    "mz" => "Mozambique",
    "mm" => "Myanmar",
    "na" => "Namibia",
    "nr" => "Nauru",
    "np" => "Nepal",
    "nl" => "Netherlands",
    "nc" => "New Caledonia",
    "nz" => "New Zealand",
    "ni" => "Nicaragua",
    "ne" => "Niger",
    "ng" => "Nigeria",
    "nu" => "Niue",
    "nf" => "Norfolk Island",
    "mk" => "North Macedonia",
    "mp" => "Northern Mariana Islands",
    "no" => "Norway",
    "om" => "Oman",
    "pk" => "Pakistan",
    "pw" => "Palau",
    "ps" => "State of Palestine",
    "pa" => "Panama",
    "pg" => "Papua New Guinea",
    "py" => "Paraguay",
    "pe" => "Peru",
    "ph" => "Philippines",
    "pn" => "Pitcairn",
    "pl" => "Poland",
    "pt" => "Portugal",
    "pr" => "Puerto Rico",
    "qa" => "Qatar",
    "re" => "Réunion",
    "ro" => "Romania",
    "ru" => "Russian Federation",
    "rw" => "Rwanda",
    "bl" => "Saint Barthélemy",
    "sh" => "Ascension and Tristan da Cunha, Saint Helena",
    "kn" => "Saint Kitts and Nevis",
    "lc" => "Saint Lucia",
    "mf" => "Saint Martin (French part)",
    "pm" => "Saint Pierre and Miquelon",
    "vc" => "Saint Vincent and the Grenadines",
    "ws" => "Samoa",
    "sm" => "San Marino",
    "st" => "Sao Tome and Principe",
    "sa" => "Saudi Arabia",
    "sn" => "Senegal",
    "rs" => "Serbia",
    "sc" => "Seychelles",
    "sl" => "Sierra Leone",
    "sg" => "Singapore",
    "sx" => "Sint Maarten (Dutch part)",
    "sk" => "Slovakia",
    "si" => "Slovenia",
    "sb" => "Solomon Islands",
    "so" => "Somalia",
    "za" => "South Africa",
    "gs" => "South Georgia and the South Sandwich Islands",
    "ss" => "South Sudan",
    "es" => "Spain",
    "lk" => "Sri Lanka",
    "sd" => "Sudan",
    "sr" => "Suriname",
    "sj" => "Svalbard and Jan Mayen",
    "se" => "Sweden",
    "ch" => "Switzerland",
    "sy" => "Syrian Arab Republic",
    "tw" => "Province of China, Taiwan",
    "tj" => "Tajikistan",
    "tz" => "United Republic of Tanzania",
    "th" => "Thailand",
    "tl" => "Timor-Leste",
    "tg" => "Togo",
    "tk" => "Tokelau",
    "to" => "Tonga",
    "tt" => "Trinidad and Tobago",
    "tn" => "Tunisia",
    "tr" => "Turkey",
    "tm" => "Turkmenistan",
    "tc" => "Turks and Caicos Islands",
    "tv" => "Tuvalu",
    "ug" => "Uganda",
    "ua" => "Ukraine",
    "ae" => "United Arab Emirates",
    "gb" => "United Kingdom of Great Britain and Northern Ireland",
    "us" => "United States of America",
    "um" => "United States Minor Outlying Islands",
    "uy" => "Uruguay",
    "uz" => "Uzbekistan",
    "vu" => "Vanuatu",
    "ve" => "Venezuela (Bolivarian Republic of)",
    "vn" => "Viet Nam",
    "vg" => "Virgin Islands (British)",
    "vi" => "Virgin Islands (U.S.)",
    "wf" => "Wallis and Futuna",
    "eh" => "Western Sahara",
    "ye" => "Yemen",
    "zm" => "Zambia",
    "zw" => "Zimbabwe"
  }

  def alpha_2_codes, do: @alpha_2_codes
end
